name: CI

on:
  push:
    branches: [main, release]
  pull_request:
    branches: [main, release]
  workflow_dispatch:

jobs:
  run-unit-tests:
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install project and dependencies
        run: make install

      - name: Run tests
        run: make test-all